// @ts-check
import { defineConfig } from 'astro/config'

import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  // Required for canonical URLs, sitemap generation, and absolute OG image URLs.
  site: 'https://www.leviacore.com',

  // Static output. There is no server, no database, and no admin login by design —
  // most of the attack surface simply does not exist. See build-context/DECISIONS.md.
  output: 'static',

  // Clean URLs with no trailing slash, matching the existing site exactly.
  // URL parity is the one non-negotiable SEO rule of this migration:
  // /project/warframe must remain /project/warframe.
  trailingSlash: 'never',

  build: {
    format: 'directory',
    // Inline only genuinely tiny stylesheets; anything larger stays a cacheable file.
    inlineStylesheets: 'auto',
  },

  image: {
    // sharp ships with Astro. Phase F targets AVIF/WebP with responsive srcset.
    responsiveStyles: true,
  },

  devToolbar: {
    enabled: false,
  },

  integrations: [
    sitemap({
      /**
       * The sitemap is generated by walking the ACTUAL build output — never a
       * hardcoded URL list. That is what keeps gate 5 of the blog enablement
       * checklist closed for free: when `features.blog` is false no blog routes
       * are emitted, so no blog URLs can appear here. See docs/enable-blog.md.
       *
       * This filter only removes pages that ARE built but must not be indexed.
       */
      filter: (page) => {
        // Dev-only component gallery. Kept in the repo because it is genuinely
        // useful for review, but it is not site content. Also carries noindex.
        if (page.includes('/dev/')) return false
        return true
      },
    }),
  ],
})