/**
 * localize-assets.mjs
 *
 * Copies original images out of the Webflow export into src/assets/images/,
 * skipping Webflow's pre-generated responsive variants (-p-500, -p-800, -p-1080),
 * which Astro's image pipeline regenerates itself at build time.
 *
 * Also emits build-context/assets.md — the asset manifest that Phase D2's
 * alt-writer agent consumes. Re-runnable and idempotent.
 *
 * Usage: node scripts/localize-assets.mjs
 */
import { readdir, mkdir, copyFile, writeFile, stat } from 'node:fs/promises'
import { join, extname, basename } from 'node:path'
import sharp from 'sharp'

const EXPORT_IMAGES = join(process.cwd(), '..', '_webflow-export', 'images')
const DEST_ASSETS = join(process.cwd(), 'src', 'assets', 'images')
const DEST_PUBLIC = join(process.cwd(), 'public')
const MANIFEST = join(process.cwd(), 'build-context', 'assets.md')

/** Webflow appends these to auto-generated responsive copies. */
const VARIANT_RE = /-p-(500|800|1080|1600|2000)$/

/** These are referenced by <link> in the document head, so they stay unhashed in public/. */
const PUBLIC_FILES = new Set(['favicon.png', 'webclip.png'])

const fmtBytes = (n) => `${(n / 1024).toFixed(1)} KB`

async function dimensions(path) {
  try {
    const { width, height, format } = await sharp(path).metadata()
    return { width, height, format }
  } catch {
    return { width: null, height: null, format: extname(path).slice(1) }
  }
}

async function main() {
  await mkdir(DEST_ASSETS, { recursive: true })
  await mkdir(DEST_PUBLIC, { recursive: true })

  const all = (await readdir(EXPORT_IMAGES)).sort()
  const originals = []
  const variants = []

  for (const file of all) {
    const stem = basename(file, extname(file))
    ;(VARIANT_RE.test(stem) ? variants : originals).push(file)
  }

  const rows = []
  for (const file of originals) {
    const src = join(EXPORT_IMAGES, file)
    const isPublic = PUBLIC_FILES.has(file)
    const dest = join(isPublic ? DEST_PUBLIC : DEST_ASSETS, file)
    await copyFile(src, dest)

    const { size } = await stat(src)
    const { width, height, format } = await dimensions(src)
    const variantCount = variants.filter(
      (v) => basename(v, extname(v)).replace(VARIANT_RE, '') === basename(file, extname(file))
    ).length

    rows.push({
      file,
      dest: isPublic ? `public/${file}` : `src/assets/images/${file}`,
      format,
      dims: width && height ? `${width}×${height}` : '—',
      size: fmtBytes(size),
      variantCount,
    })
  }

  const md = [
    '# Asset Manifest',
    '',
    '<!-- GENERATED by scripts/localize-assets.mjs — do not hand-edit the table.',
    '     The Alt Text column IS hand-edited: Phase D2 fills it in. -->',
    '',
    `Source: \`_webflow-export/images/\` · ${all.length} files total`,
    `Copied: **${originals.length} originals**. Skipped **${variants.length} Webflow responsive variants**`,
    "(`-p-500`, `-p-800`, `-p-1080`) — Astro's image pipeline regenerates these at build time with AVIF/WebP",
    'and correct `srcset`, so shipping Webflow\'s copies would be redundant weight.',
    '',
    '## Originals',
    '',
    '| # | File | Destination | Format | Dimensions | Size | WF variants | Alt Text (Phase D2) |',
    '|---|---|---|---|---|---|---|---|',
    ...rows.map(
      (r, i) =>
        `| ${i + 1} | \`${r.file}\` | \`${r.dest}\` | ${r.format} | ${r.dims} | ${r.size} | ${r.variantCount} | ⬜ TODO |`
    ),
    '',
    '## Notes',
    '',
    '- `favicon.png` and `webclip.png` go to `public/` because they are referenced by `<link>` in the',
    '  document head and must keep stable, unhashed filenames.',
    '- Everything else goes to `src/assets/images/` so Astro can optimize and hash it.',
    '- **Not included here:** the five case study hero images. Those live on the Webflow CDN and did not',
    '  export. They arrive with the Projects CSV (Open Item #6). Do not delete the Webflow site until they',
    '  have been downloaded and verified.',
    '- The Open Graph / Twitter card image is currently hosted at `i.imgur.com` and must also be localized.',
    '',
  ].join('\n')

  await writeFile(MANIFEST, md, 'utf8')

  console.log(`Copied ${originals.length} originals (${variants.length} variants skipped)`)
  console.log(`Manifest: build-context/assets.md`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
